#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Private dashboard installer — one file, and a config.json.

    python3 installeur-tableau-de-bord.py                 # shows what it would do
    python3 installeur-tableau-de-bord.py --installer     # does it

It writes the files, draws an icon with your initials, produces the figures once, then — with
--installer — starts the container, opens access to the tailnet and sets the morning task.
Every missing step is named, none of them is compulsory.

⛔ This file is GENERATED by scripts/faire-installeur.py. Do not edit it by hand: the next
build would wipe your changes.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

PAQUET = {}  # REMPLACE_A_LA_FABRICATION

PORT = 8090
VERT, ROUGE, OR, GRIS, NET = "\033[32m", "\033[31m", "\033[33m", "\033[90m", "\033[0m"


def dire(etat: str, texte: str, detail: str = "") -> None:
    c = {"ok": VERT, "non": ROUGE, "info": OR, "gris": GRIS}.get(etat, "")
    marque = {"ok": "✓", "non": "✗", "info": "•", "gris": " "}.get(etat, " ")
    print(f" {c}{marque}{NET} {texte}" + (f"\n     {GRIS}{detail}{NET}" if detail else ""))


def commande(nom: str) -> str | None:
    return shutil.which(nom)


def lancer(args: list[str], cwd: Path | None = None) -> tuple[int, str]:
    try:
        r = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=300)
        return r.returncode, (r.stdout + r.stderr).strip()
    except Exception as exc:
        return 1, str(exc)


# ── 1. What the machine can do ─────────────────────────────────────────────────────────
def controler() -> dict:
    etat = {}
    etat["python"] = sys.version_info >= (3, 9)
    dire("ok" if etat["python"] else "non",
         f"Python {sys.version_info.major}.{sys.version_info.minor}",
         "" if etat["python"] else "3.9 or later: zoneinfo handles local days")
    for mod, pour in (("requests", "App Store listings and versions"),
                      ("cryptography", "signing the App Store key"),
                      ("PIL", "icon with the right initials")):
        try:
            __import__(mod)
            etat[mod] = True
            dire("ok", f"{mod} — {pour}")
        except ImportError:
            etat[mod] = False
            dire("info", f"{mod} missing — {pour}",
                 f"pip3 install {'pillow' if mod == 'PIL' else mod}")
    for outil, pour in (("docker", "serving the page"), ("tailscale", "reaching it by phone")):
        etat[outil] = bool(commande(outil))
        dire("ok" if etat[outil] else "info", f"{outil} — {pour}",
             "" if etat[outil] else "optional: the page can be served by anything")
    return etat


# ── 2. The files ───────────────────────────────────────────────────────────────────────
def poser_fichiers(cible: Path, faire: bool) -> None:
    for chemin, contenu in PAQUET["textes"].items():
        f = cible / chemin
        dire("gris", f"{chemin}  ({len(contenu) // 1024 or 1} kB)")
        if faire:
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(contenu, encoding="utf-8")
            if chemin.endswith(".py"):
                f.chmod(0o755)
    for chemin, b64 in PAQUET["images"].items():
        octets = base64.b64decode(b64)
        dire("gris", f"{chemin}  ({len(octets) // 1024} kB)")
        if faire:
            f = cible / chemin
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_bytes(octets)


# ── 3. The icon, with the configuration's initials ─────────────────────────────────────
def faire_icone(cible: Path, conf: dict, faire: bool) -> None:
    """The shipped PNGs carry "AB" and "cd". If Pillow is here, we redraw them as yours.

    ⚠️ Without Pillow the home screen keeps the original initials: it is an image, not text,
    and no configuration changes it afterwards.
    """
    m = conf.get("marque") or {}
    haut, bas = (m.get("haut") or "AB")[:2], (m.get("bas") or "cd")[:2]
    accent = conf.get("accent") or "#E8972E"
    if haut == "AB" and bas == "cd":
        dire("gris", "icon: original initials, nothing to redraw")
        return
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        dire("info", "icon: Pillow missing, it will keep \"AB · cd\"",
             "pip3 install pillow, then run again")
        return
    dire("ok", f"icon redrawn: \"{haut}\" and \"{bas}\", rule {accent}")
    if not faire:
        return
    rvb = tuple(int(accent.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    police = None
    for essai in ("/System/Library/Fonts/Supplemental/Arial Black.ttf",
                  "/System/Library/Fonts/Helvetica.ttc",
                  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"):
        if Path(essai).exists():
            police = essai
            break
    for taille in (180, 512):
        k = taille / 64
        im = Image.new("RGB", (taille, taille), (0, 0, 0))
        d = ImageDraw.Draw(im)
        f = ImageFont.truetype(police, int(30 * k)) if police else ImageFont.load_default()
        for texte, x, y in ((haut, 32, 30), (bas, 48, 58)):
            b = d.textbbox((0, 0), texte, font=f)
            d.text(((x * k) - (b[2] - b[0]) / 2, (y * k) - b[3]), texte, font=f,
                   fill=(237, 235, 228))
        d.rounded_rectangle([5 * k, 38 * k, 23 * k, 45 * k], radius=2 * k, fill=rvb)
        im.save(cible / "tableau-de-bord" / f"icone-{taille}.png", optimize=True)


# ── 4. The service ─────────────────────────────────────────────────────────────────────
COMPOSE = """services:
  tableau:
    image: nginx:alpine
    # ⛔ 127.0.0.1 and not 0.0.0.0: the door to the private network is opened by
    # `tailscale serve`, never by a port listening on every interface.
    ports:
      - "127.0.0.1:%d:80"
    volumes:
      - ./tableau-de-bord:/usr/share/nginx/html:ro
      - ./tableau-de-bord/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
""" % PORT


def servir(cible: Path, etat: dict, faire: bool) -> None:
    f = cible / "docker-compose.tableau.yml"
    dire("gris", f"docker-compose.tableau.yml  (port 127.0.0.1:{PORT})")
    if faire:
        f.write_text(COMPOSE, encoding="utf-8")
    if not etat.get("docker"):
        dire("info", "docker missing — serve tableau-de-bord/ with whatever you like",
             f"par exemple : cd tableau-de-bord && python3 -m http.server {PORT} --bind 127.0.0.1")
        return
    if not faire:
        dire("info", f"would start the container on 127.0.0.1:{PORT}")
        return
    code, sortie = lancer(["docker", "compose", "-f", str(f), "up", "-d",
                           "--force-recreate", "tableau"], cwd=cible)
    dire("ok" if code == 0 else "non", "container started" if code == 0 else "container failed",
         "" if code == 0 else sortie[-300:])


# ── 5. Private access ──────────────────────────────────────────────────────────────────
def ouvrir_au_tailnet(etat: dict, faire: bool) -> None:
    if not etat.get("tailscale"):
        dire("info", "tailscale missing — the page stays on the machine",
             "https://tailscale.com, then run again")
        return
    if not faire:
        dire("info", f"would open access: tailscale serve --bg --https=443 http://127.0.0.1:{PORT}")
        return
    code, sortie = lancer(["tailscale", "serve", "--bg", "--https=443",
                           f"http://127.0.0.1:{PORT}"])
    if code != 0:
        dire("non", "tailscale serve failed", sortie[-300:])
        return
    _, etat_serve = lancer(["tailscale", "serve", "status"])
    prive = "tailnet only" in etat_serve
    dire("ok" if prive else "non",
         "open to the private network alone" if prive else "⚠️ CHECK: this is not tailnet only",
         etat_serve.splitlines()[0] if etat_serve else "")
    # ⛔ On ne propose JAMAIS « tailscale funnel » : il publierait ces chiffres sur Internet.


# ── 6. The morning refresh ─────────────────────────────────────────────────────────────
def poser_la_tache(cible: Path, heure: int, faire: bool) -> None:
    ligne = f"{0} {heure} * * * cd {cible} && {sys.executable} scripts/tableau-de-bord.py >/dev/null 2>&1"
    dire("gris", f"task: every day at {heure}:00")
    if not faire:
        dire("info", "would add this line to the crontab", ligne)
        return
    code, actuel = lancer(["crontab", "-l"])
    lignes = [l for l in (actuel.splitlines() if code == 0 else []) if "tableau-de-bord.py" not in l]
    lignes.append(ligne)
    p = subprocess.run(["crontab", "-"], input="\n".join(lignes) + "\n", text=True,
                       capture_output=True)
    dire("ok" if p.returncode == 0 else "non",
         f"task set for {heure}:00" if p.returncode == 0 else "crontab refused",
         "" if p.returncode == 0 else p.stderr[-200:])


# ── 7. The figures, a first time ───────────────────────────────────────────────────────
def premiers_chiffres(cible: Path, faire: bool) -> None:
    if not faire:
        dire("info", "would produce the figures a first time")
        return
    code, sortie = lancer([sys.executable, "scripts/tableau-de-bord.py"], cwd=cible)
    for l in sortie.splitlines():
        dire("gris", l.strip())
    dire("ok" if code == 0 else "non",
         "figures produced" if code == 0 else "the generator failed")


def main() -> int:
    ap = argparse.ArgumentParser(description="Installs the private dashboard.")
    ap.add_argument("--installer", action="store_true",
                    help="actually do it (without this flag, nothing is written)")
    ap.add_argument("--vers", default=".", help="the install directory (default: here)")
    ap.add_argument("--config", default=None, help="the config.json (default: <vers>/tableau-de-bord/config.json)")
    ap.add_argument("--heure", type=int, default=5, help="hour of the refresh (default: 5)")
    ap.add_argument("--sans-tache", action="store_true",
                    help="ne pas toucher au crontab (launchd, systemd, GitHub Actions…)")
    a = ap.parse_args()

    cible = Path(os.path.expanduser(a.vers)).resolve()
    faire = a.installer
    conf_f = Path(a.config) if a.config else cible / "tableau-de-bord" / "config.json"

    print(f"\n{OR}Private dashboard{NET} — {'install' if faire else 'dry run'}")
    print(f"{GRIS}into {cible}{NET}\n")
    if not faire:
        print(f"{GRIS}Nothing will be written. Add --installer to do it.{NET}\n")

    print("── What the machine can do")
    etat = controler()
    if not etat["python"]:
        return 1

    print("\n── The configuration")
    if conf_f.exists():
        conf = json.loads(conf_f.read_text(encoding="utf-8"))
        dire("ok", f"{conf_f}", f"title \"{conf.get('titre', '—')}\", "
                                f"{len(conf.get('sites', []))} site(s)")
    else:
        conf = json.loads(PAQUET["textes"]["tableau-de-bord/config.exemple.json"])
        dire("info", "no config.json — the example will be the starting point",
             "edit tableau-de-bord/config.json, then run again")

    print("\n── The files")
    poser_fichiers(cible, faire)
    if faire and not conf_f.exists():
        conf_f.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(cible / "tableau-de-bord" / "config.exemple.json", conf_f)
        dire("ok", "config.json created from the example")
    faire_icone(cible, conf, faire)

    print("\n── The figures")
    premiers_chiffres(cible, faire)

    print("\n── The service")
    servir(cible, etat, faire)

    print("\n── Private access")
    ouvrir_au_tailnet(etat, faire)

    print("\n── The morning")
    if a.sans_tache:
        dire("gris", "crontab left alone; schedule it as you see fit",
             f"{sys.executable} scripts/tableau-de-bord.py")
    else:
        poser_la_tache(cible, a.heure, faire)

    print()
    if faire:
        code, st = lancer(["tailscale", "serve", "status"]) if etat.get("tailscale") else (1, "")
        adresse = next((l.split()[0] for l in st.splitlines() if l.startswith("https://")), None)
        if adresse:
            print(f"{VERT}Ready.{NET} {adresse}")
            print(f"{GRIS}On iPhone: open it in Safari, then Share → Add to Home Screen.{NET}")
        else:
            print(f"{VERT}Ready.{NET} http://127.0.0.1:{PORT}")
    else:
        print(f"{OR}Dry run finished.{NET} Run again with --installer to do it.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
